"""adiciona tabelas family e family_members

Revision ID: e8baa849b0c5
Revises: cd7926035aab
Create Date: 2026-04-30 13:22:06.655070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8baa849b0c5'
down_revision = 'cd7926035aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_family_member')
    )
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_members_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_members_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_family_members_family_id'))

    op.drop_table('family_members')
    op.drop_table('families')
    # ### end Alembic commands ###
